version: "3.8"

services:
  pyspark:
    build: .
    command:
      - /bin/bash
      - -c
      - |
        apt update -y 
        apt upgrade -y
        apt install default-jdk -y
        python3 load_data.py
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - elevatus
  
  db:
    container_name: mongo 
    image: mongo
    restart: always
    networks:
      - elevatus
    ports:
      - '6001:27017'

volumes:
  mongo:


networks:
  elevatus:
    name: elevatus
    driver: bridge